mkdir -p .streamlit
echo 'GITHUB_TOKEN = "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"' > .streamlit/secrets.toml# .streamlit/secrets.toml
GITHUB_TOKEN = "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"  # Use o mesmo nome que no código
